name: shop
description: "A new Flutter project."
publish_to: 'none' 

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  


  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  cookie_jar: ^4.0.8
  shared_preferences: ^2.5.3
  image_picker_android: ^0.8.12+23
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/shoes.png
    - .env


